-- reminder that files imported by lazy.nvim are processed in alphabetical order
-- default mappings from astrocommunity will be negated here for a cleaner config
---@type LazySpec
return {
  -- motion
  { import = "astrocommunity.motion.mini-surround" }, -- don't know how to handle manually
  -- lsp?/editing?
  { import = "astrocommunity.lsp.inc-rename-nvim" },
  -- IDEA: make a pr to make it possible to know how long until LSPs get killed,
  -- add a timer on the statusline that appears after 5 minutes of inactivity
  -- {
  --   { import = "astrocommunity.lsp.garbage-day-nvim" },
  --   {
  --     "astrocore",
  --     opts = {
  --       commands = {
  --         LsStart = {
  --           function() require("garbage-day.utils").start_lsp() end,
  --           desc = "Starts up lspconfig and none-ls language servers",
  --         },
  --         LsStop = {
  --           function() require("garbage-day.utils").stop_lsp() end,
  --           desc = "Stops lspconfig and none-ls language servers",
  --         },
  --       },
  --     },
  --   },
  -- },
  { import = "astrocommunity.editing-support.zen-mode-nvim" },
  -- since this is only mappings, it's mappings won't be negated
  { import = "astrocommunity.recipes.neovide" },
  -- https://github.com/chikko80/error-lens.nvim
  -- https://github.com/NvChad/nvcommunity/tree/main/lua/nvcommunity/editor/beacon
  -- https://github.com/NvChad/nvcommunity/tree/main/lua/nvcommunity/editor/biscuits
  -- https://github.com/NvChad/nvcommunity/tree/main/lua/nvcommunity/editor/symbols-outline
  -- https://github.com/NvChad/nvcommunity/tree/main/lua/nvcommunity/editor/treesittercontext
  -- https://github.com/NvChad/nvcommunity/tree/main/lua/nvcommunity/editor/undo
  -- https://github.com/NvChad/nvcommunity/tree/main/lua/nvcommunity/editor/fold-cycle
  -- https://github.com/NvChad/nvcommunity/tree/main/lua/nvcommunity/editor/fold-preview
  -- https://github.com/NvChad/nvcommunity/tree/main/lua/nvcommunity/editor/origami
  -- https://github.com/NvChad/nvcommunity/tree/main/lua/nvcommunity/editor/tailwindfold
  -- https://github.com/NvChad/nvcommunity/tree/main/lua/nvcommunity/editor/lazygit
  -- https://github.com/NvChad/nvcommunity/tree/main/lua/nvcommunity/lsp/codeactionmenu
  -- https://github.com/NvChad/nvcommunity/tree/main/lua/nvcommunity/lsp/barbecue
  -- https://github.com/NvChad/nvcommunity/tree/main/lua/nvcommunity/lsp/dim
  -- https://github.com/NvChad/nvcommunity/tree/main/lua/nvcommunity/lsp/lspsaga
  -- https://github.com/NvChad/nvcommunity/tree/main/lua/nvcommunity/lsp/lspui
  -- https://github.com/NvChad/nvcommunity/tree/main/lua/nvcommunity/lsp/prettyhover
  -- https://github.com/NvChad/nvcommunity/tree/main/lua/nvcommunity/motion/bookmarks
  -- https://github.com/NvChad/nvcommunity/tree/main/lua/nvcommunity/tools/conjure
  -- https://github.com/Olical/nfnl
  -- https://github.com/roobert/hoversplit.nvim
  -- https://github.com/lewis6991/hover.nvim
  -- https://github.com/soulis-1256/eagle.nvim
  -- https://github.com/amrbashir/nvim-docs-view
  -- https://github.com/neovim/nvimdev.nvim
  -- https://github.com/nvimdev/epo.nvim
  -- https://github.com/nvimdev/lspsaga.nvim
  -- https://github.com/nvimdev/dashboard-nvim
  -- https://github.com/nvimdev/guard.nvim
  -- https://github.com/nvimdev/hlsearch.nvim
  -- https://github.com/luackasRanarison/nvim-devdocs
  -- https://github.com/3rd/image.nvim
  -- https://github.com/00sap/visual.nvim
}
