# would be nice to have dynamic colorschemes
# TODO: use wallust colors
format = """
[](fg:#3B4252)\
$username\
$hostname\
$shell\
[](fg:#3B4252 bg:#4C566A)\
$directory\
[](fg:#4C566A bg:#86BBD8)\
$git_branch\
$git_commit\
$git_status\
$git_state\
[](fg:#86BBD8)\
$sudo\
$nix_shell\
$cmd_duration\
$line_break\
$jobs\
$character\
"""
command_timeout = 5000
add_newline = true

[username]
style_user = "white"
format = '[$user]($style bg:#3B4252)'

[hostname]
style = "bg:#3B4252"
format = "[@$hostname ]($style)"

[shell]
disabled = false
bash_indicator = ">_ "
fish_indicator = "><>"
zsh_indicator = "%_ "
powershell_indicator = ">>>"
cmd_indicator = "<<<"
unknown_indicator = "?_ "
style = "bg:#3B4252"
format = "[$indicator]($style)"

[directory]
truncation_length = 5
style = "bg:#4C566A"
format = "[ $path ]($style)"

[git_branch]
style = "bg:#86BBD8 fg:#3B4252"
format = '[ $symbol$branch ]($style)'

[git_commit]
style = "bg:#86BBD8 fg:#3B4252"
format = '[ $hash ]($style)'

[git_status]
style = "bg:#86BBD8 fg:#3B4252"
format = '[$all_status$ahead_behind]($style)'

[git_state]
style = "bg:#86BBD8 fg:#3B4252"
format = '[ $state($progress_current/$progress_total)]($style)'

[sudo]
allow_windows = true
disabled = false
symbol = '!'
# style = 'bold green'
format = '[ $symbol]($style)'

[nix_shell]
impure_msg = '[❄️](bold blue)'
pure_msg = '[❄️](bold green)'
unknown_msg = '[❄️](bold yellow)'
format = ' $state'

[cmd_duration]
min_time = 500
style = "fg:#eb7442"
format = " took [$duration]($style)"

[line_break]

[jobs]

[character]
success_symbol = '[-](bold green)'
# would be nice to have sudo module ehre
error_symbol = '[✕](bold red)'
vimcmd_symbol = '[N](bold blue) '
vimcmd_replace_one_symbol = '[R](bold red) '
vimcmd_replace_symbol = '[R](bold red) '
vimcmd_visual_symbol = "[V ](bold yellow)"
