config_version = 12

[backdrop]
enabled = true
tint_intensity = 0.0

[bar.default]
background_opacity = 0.89999997988343239
center = [ "media", "group:g1", "widget_2" ]
end = [ "notifications", "volume", "battery", "clock", "tray" ]
layer = "overlay"
margin_ends = 0
padding = 12
position = "left"
radius = 20
radius_bottom_left = 0
radius_top_left = 0
reserve_space = false
show_on_workspace_switch = false
smart_auto_hide = true
start = [ "control-center", "workspaces" ]
thickness = 42
widget_spacing = 12

    [bar.default.dead_zone.actions]
    left = "exec noctalia msg panel-toggle launcher"
    right = "none"

    [[bar.default.capsule_group]]
    accordion = false
    accordion_direction = "end"
    enabled = true
    fill = "surface_variant"
    id = "g1"
    members = [ "widget", "bar" ]
    opacity = 1.0
    padding = 6.0

[battery]
warning_threshold = 15

[control_center]
hidden_tabs = [
    "media",
    "audio",
    "monitor",
    "system",
    "power",
    "network",
    "bluetooth",
    "weather",
    "calendar",
    "notifications",
    "screen-time"
]
sidebar = "none"
sidebar_section = "none"
width = 750

    [[control_center.shortcuts]]
    type = "wifi"

    [[control_center.shortcuts]]
    type = "bluetooth"

    [[control_center.shortcuts]]
    type = "caffeine"

    [[control_center.shortcuts]]
    type = "nightlight"

[desktop_widgets]
enabled = false

[hooks]
started = "noctalia msg wallpaper-set .cache/wallpaper"

[hot_corners.top_left]
action = "control_center"

[idle]
behavior_order = [ "lock", "screen-off", "lock-and-suspend" ]
pre_action_fade_seconds = 5

    [idle.behavior.lock]
    action = "lock"
    enabled = true
    timeout = 60.0

    [idle.behavior.lock-and-suspend]
    action = "lock_and_suspend"
    enabled = true
    timeout = 300.0

    [idle.behavior.screen-off]
    action = "screen_off"
    enabled = true
    timeout = 180.0

[location]
custom_schedule = true
sunrise = "06:00"
sunset = "22:00"

[lockscreen]
blurred_desktop = true
tint_intensity = 0.0

[lockscreen_widgets]
enabled = true
schema_version = 2
widget_order = [
    "lockscreen-login-box@DP-1",
    "lockscreen-login-box@eDP-1",
    "lockscreen-widget-0000000000000001",
    "lockscreen-widget-0000000000000002",
    "lockscreen-widget-0000000000000003"
]

    [lockscreen_widgets.grid]
    cell_size = 16
    major_interval = 4
    visible = true

    [lockscreen_widgets.widget."lockscreen-login-box@DP-1"]
    box_height = 196.0
    box_width = 720.0
    cx = 960.0
    cy = 961.0
    output = "DP-1"
    rotation = 0.0
    type = "login_box"

        [lockscreen_widgets.widget."lockscreen-login-box@DP-1".settings]
        background_color = "surface_variant"
        background_opacity = 0.88
        background_radius = 12.0
        center_password_text = false
        input_opacity = 1.0
        input_radius = 6.0
        layout = "regular"
        show_caps_lock = true
        show_keyboard_layout = true
        show_login_button = true
        show_media = true
        show_session_buttons = true
        show_unlock_hint = true
        show_weather = true

    [lockscreen_widgets.widget."lockscreen-login-box@eDP-1"]
    box_height = 128.0
    box_width = 720.0
    cx = 800.0
    cy = 881.0
    output = "eDP-1"
    rotation = 0.0
    type = "login_box"

        [lockscreen_widgets.widget."lockscreen-login-box@eDP-1".settings]
        background_color = "surface_variant"
        background_opacity = 0.88
        background_radius = 12.0
        center_password_text = true
        input_opacity = 1.0
        input_radius = 6.0
        layout = "regular"
        show_caps_lock = true
        show_keyboard_layout = true
        show_login_button = false
        show_media = false
        show_session_buttons = true
        show_unlock_hint = true
        show_weather = false

    [lockscreen_widgets.widget.lockscreen-widget-0000000000000001]
    box_height = 96.0
    box_width = 240.0
    cx = 800.0
    cy = 500.0
    output = "eDP-1"
    rotation = 0.0
    type = "clock"

        [lockscreen_widgets.widget.lockscreen-widget-0000000000000001.settings]
        background = false
        background_opacity = 0.80000000000000004
        center_text = false
        color = "surface_variant"

    [lockscreen_widgets.widget.lockscreen-widget-0000000000000002]
    box_height = 128.0
    box_width = 384.0
    cx = 288.0
    cy = 500.0
    output = "eDP-1"
    rotation = 0.0
    type = "media_player"

        [lockscreen_widgets.widget.lockscreen-widget-0000000000000002.settings]
        background = true
        hide_when_no_media = true

    [lockscreen_widgets.widget.lockscreen-widget-0000000000000003]
    box_height = 128.0
    box_width = 80.0
    cx = 384.0
    cy = 881.0
    output = "eDP-1"
    rotation = 0.0
    type = "yocraft/battery-widget:widget"

        [lockscreen_widgets.widget.lockscreen-widget-0000000000000003.settings]
        background = true
        background_color = "surface"
        background_opacity = 0.80000000000000004
        background_padding = 10
        background_radius = 12
        battery = "auto"
        battery_name = "BAT0"
        charging_color = "on_surface"
        color = "on_surface"
        hide_full = true
        hide_plugged = false
        layout = "vertical"
        refresh_interval = 60
        show_glyph = true
        show_label = true
        warning_color = "error"

[nightlight]
enabled = true

[notification]
layer = "overlay"

[osd]
position = "bottom_center"

[plugin_settings."alexander/screen-toolkit"]
panel-full_open_near_click = true
panel-full_placement = "attached"
panel_open_near_click = true
panel_placement = "attached"
result_open_near_click = true
result_placement = "attached"

[plugin_settings."frai3mega/battery-graph"]
battery-panel_open_near_click = true
battery-panel_placement = "attached"

[plugin_settings."whyoolw/sharednd"]
only_active = true

[plugin_settings."yocraft/qrcode"]
panel_open_near_click = true
panel_placement = "attached"

[plugins]
enabled = [ "elijaharch/wl-screen-mirror", "noctalia/kaomoji", "yocraft/battery-widget", "whyoolw/sharednd" ]

[shell]
button_borders = false
clipboard_auto_paste = "off"
input_borders = false
niri_overview_type_to_launch_enabled = true
password_style = "random"
polkit_agent = true
popup_borders = false
screen_time_enabled = true
show_location = false

    [shell.launcher]
    app_grid = true
    fetch_exchange_rates = false
    sort_by_usage = false

        [shell.launcher.providers.calculator]
        global = false

    [shell.panel]
    clipboard_placement = "attached"
    launcher_placement = "attached"
    open_near_click_clipboard = true
    open_near_click_control_center = true
    open_near_click_launcher = true
    open_near_click_session = true
    open_near_click_wallpaper = true
    polkit_placement = "attached"
    session_position = "center"

    [shell.screenshot]
    copy_to_clipboard = false
    freeze_screen = false
    save_to_file = false

    [shell.session]
    grid = true

        [[shell.session.actions]]
        action = "lock"
        countdown_seconds = 0.0
        enabled = true
        shortcut = "1"
        variant = "default"

        [[shell.session.actions]]
        action = "logout"
        countdown_seconds = 5.0
        enabled = true
        shortcut = "2"
        variant = "default"

        [[shell.session.actions]]
        action = "command"
        command = "systemctl hibernate"
        countdown_seconds = 5.0
        enabled = true
        glyph = "zzz"
        label = "Hibernate"
        shortcut = "3"
        variant = "default"

        [[shell.session.actions]]
        action = "suspend"
        countdown_seconds = 5.0
        enabled = true
        shortcut = "4"
        variant = "default"

        [[shell.session.actions]]
        action = "reboot"
        countdown_seconds = 5.0
        enabled = true
        shortcut = "5"
        variant = "default"

        [[shell.session.actions]]
        action = "shutdown"
        countdown_seconds = 5.0
        enabled = true
        shortcut = "6"
        variant = "default"

[systemd.monitor]
enabled = true

[theme]
mode = "dark"
source = "wallpaper"
wallpaper_scheme = "m3-tonal-spot"

    [theme.templates]
    builtin_ids = [ "alacritty", "btop", "gtk3", "gtk4", "kcolorscheme", "qt", "starship" ]

[wallpaper]
directory = "/home/u/Pictures/wallpapers"
transition_on_startup = true

    [wallpaper.default]
    path = "/home/u/.cache/wallpaper"

    [wallpaper.last]
    path = "/home/u/.cache/wallpaper"

    [wallpaper.monitors.eDP-1]
    path = "/home/u/.cache/wallpaper"

[weather]
enabled = false

[widget.bar]
type = "icefish/phone-connect:bar"

[widget.battery]
display_mode = "graphic"
show_label = false

    [widget.battery.actions]
    right = "panel-toggle control-center monitor"

[widget.bluetooth]
enabled = false

[widget.brightness]
show_label = false

[widget.clock.actions]
right = "panel-toggle control-center screen-time"

[widget.control-center]
custom_image = "/home/u/.config/etc/home/noctalia/NixOS.svg"
custom_image_colorize = true
scale = 1.4000000000000001

    [widget.control-center.actions]
    right = "panel-toggle control-center system"

[widget.media]
art_size = 30
hide_when_no_media = true

[widget.network]
enabled = false

[widget.tray]
drawer = true
drawer_item_size = 20.0
scale = 1.1500000000000001

[widget.volume]
show_label = false

[widget.widget]
type = "alexander/screen-toolkit:widget"

[widget.widget_2]
type = "yocraft/qrcode:widget"

[widget.workspaces]
focused_output_only = true
hide_when_empty = true
show_labels = false

    [widget.workspaces.actions]
    right = "exec niri msg action toggle-overview"