general {
    hide_cursor = true
    ignore_empty_input = true
}

auth {
    fingerprint:enabled = true
}

background {
    path = screenshot
    blur_passes = 2
    blur_size = 4
}

input-field {
    monitor =
    size = 35%, 30%
    placeholder_text = <i>$TIME</i>
    outline_thickness = 0
    check_color = rgba(205, 136, 34, 1)
    inner_color = rgba(0, 0, 0, 0.0) # no fill

    font_color = rgb(143, 143, 143)
    fade_on_empty = false
    fade_timeout = 5000
    rounding = 15

    halign = center
    valign = center
}
