general {
    # loginctl handlers
    unlock_cmd = pkill -SIGUSR1 hyprlock
    before_sleep_cmd = sh -c 'pkill hyprlock -SIGUSR1; noctalia-shell ipc call lockScreen lock || noctalia msg session lock'
}
