auto_sync = false
dialect = "uk"
enter_accept = false
keymap_mode = "vim-insert"
sync_address = ""
update_check = false
workspaces = true

[keymap_cursor]
emacs = "blink-block"
vim_insert = "blink-block"
vim_normal = "steady-block"
